name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r module-$(echo ${{ github.ref_name }} | sed 's/^v//').zip \
          service.sh \
          post-fs-data.sh \
          module.prop \
          customize.sh \
          META-INF/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            module-*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 