name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temporary directory and copy files
        run: |
          mkdir -p temp_module
          cp -r service.sh post-fs-data.sh module.prop customize.sh META-INF temp_module/

      - name: Create zip file
        run: |
          cd temp_module
          zip -r ../sshd-magisk-$(echo ${{ github.ref_name }} | sed 's/^v//').zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sshd-magisk-*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 